### ISSUE TITLE
Uploading TV shows

### ISSUE THREAD

**Issue by memo330179** [memo330179/Nuve#1]
Uploading movies seems like a pretty straight forward process, but tv shows are a little different.

When uploading show episodes should we automatically add folders or should the user add folders before adding the episode?

For example: if the episode is Futurama season 1 episode 1 should we

- Create a Futurama Folder, Create a Season 1 Folder
- Have the user create a folder called futurama, and a folder for season 1

The difference between the two options is making the call to TMDB. The latter would be more accurate but more work for the user.

**Comment by RobertHosking** [comment]
Here's what I imagined.

User selects 1 or more source folders which we index for content periodically. These folders may not be organized in any way. Assume its someone's torrent downloads folder and they don't rename any of the files. 

User can also specify a folder where uploads will go. This folder defaults to one of the above folders, but is configurable.

Every step of the way should minimize USER effort. So when we upload a file, the app does its best to guess what it is and just tosses it in a folder with the rest. 

If a user cares about file organization, they will do it manually. They are using our app because it does the organizing for them up font.

In a later feature, we could add an option to auto organize directories. (Move files on the drive and name them appropriately. Then future files would go in their expected place.) Until then, assume no organization and just plop files wherever they fit.

**Comment by memo330179** [comment]
So this means there is only one upload button instead of many per se?

**Comment by RobertHosking** [comment]
Yes. The upload just places the file in the scan folder. We can call scan() after uploading.

**Comment by RobertHosking** [comment]
This will be handled with directory scanning. (See #4)
